Update package.json and build scripts

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -11,7 +11,7 @@ sass_dir="_sass"
 vendor="assets/vendor"
 node_modules="node_modules"
 
-
+echo "==> Checking if bundle is installed..."
 # Install bundle, if not already installed
 if ! command -v bundle >/dev/null 2>&1; then
     echo "==> Installing Ruby Bundle..."
@@ -20,10 +20,9 @@ if ! command -v bundle >/dev/null 2>&1; then
         exit 1
     }
     #rbenv rehash
-else
-    echo "==> Bundle already installed, skipping..."
 fi
 
+echo "==> Setting bundle config..."
 # Set bundle path to vendor/bundle, if not already set
 bundle config set --local path 'vendor/bundle' || {
     echo "Failed to set bundle path!"
@@ -38,64 +37,58 @@ bundle config set --local jobs 4 || {
     exit 1
 }
 
-# Install gems
-if [ -f "Gemfile" ]; then
-    echo "==> Checking for gems..."
-    
-    # Install gems using variables set in .bundle/config
-    bundle install --gemfile Gemfile --retry 3 --jobs 4 2>&1 || {
-        echo "Failed to bundle gems!"
-        exit 1
-    }
-    # Deprecated
-    # bundle check >/dev/null 2>&1 || {
-    #     echo "==> Installing gems..."
-    #     
-    #     # Install gems using variables set in .bundle/config
-    #     bundle install --gemfile Gemfile --retry 3 --jobs 4 2>&1 || {
-    #         echo "Failed to bundle gems!"
-    #         exit 1
-    #     }
-    # }
-else
-    echo "==> No Gemfile found, skipping gem install..."
+# Install gems using variables set in .bundle/config
+bundle install --gemfile Gemfile --retry 3 --jobs 4 2>&1 || {
+    echo "Failed to bundle gems!"
+    exit 1
+}
+
+# Deprecated
+# bundle check >/dev/null 2>&1 || {
+#     echo "==> Installing gems..."
+#     
+#     # Install gems using variables set in .bundle/config
+#     bundle install --gemfile Gemfile --retry 3 --jobs 4 2>&1 || {
+#         echo "Failed to bundle gems!"
+#         exit 1
+#     }
+# }
+
+# Check if npm is installed
+echo "==> Checking if npm is installed..."
+if ! command -v npm >/dev/null 2>&1; then
+    echo "==> npm is not installed..."
+    exit 1
 fi
 
-# install node modules if they are not already installed
-if [ ! -d "$node_modules" ]; then
-    if ! command -v npm >/dev/null 2>&1; then
-        echo "==> npm is not installed..."
-        exit 1
-    fi
-    
-    # Install yarn if it is not already installed
-    # if ! command -v yarn >/dev/null 2>&1; then
-    #     echo "==> Installing yarn..."
-    #     
-    #     npm install -g yarn || {
-    #         echo "Failed to install yarn!"
-    #         exit 1
-    #     }
-    # fi
-    
-    # Install node modules
-    npm install || {
-        echo "Failed to install npm dependencies."
-        exit 1
-    }
-    
-    # Deprecated
-    # if [ -f "yarn.lock" ]; then
-    #     echo "==> Installing node modules with yarn..."
-    #     
-    #     yarn install --frozen-lockfile | grep -v warning || {
-    #         echo "Failed to install npm dependencies."
-    #         exit 1
-    #     }
-    # fi
-fi
+# Install yarn, if not already installed
+# if ! command -v yarn >/dev/null 2>&1; then
+#     echo "==> installing yarn..."
+#     
+#     npm install -g yarn || {
+#         echo "failed to install yarn!"
+#         exit 1
+#     }
+# fi
+
+# Install npm dependencies
+echo "==> Installing npm dependencies..."
+npm install || {
+    echo "Failed to install npm dependencies."
+    exit 1
+}
+# Deprecated: Install node modules with yarn
+# if [ -f "yarn.lock" ]; then
+#     echo "==> installing node modules with yarn..."
+#     
+#     yarn install --frozen-lockfile | grep -v warning || {
+#         echo "failed to install npm dependencies."
+#         exit 1
+#     }
+# fi
 
 # Build site assets
+echo "==> Running build script..."
 scripts/build || {
     echo "Failed to build vendor assets."
     exit 1
